"""empty message

Revision ID: d06e6c757ead
Revises: c7ed3b288562
Create Date: 2017-03-12 05:46:11.643802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06e6c757ead'
down_revision = 'c7ed3b288562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('pic', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('userid', sa.String(length=7), nullable=False))
    op.add_column('user_profile', sa.Column('username', sa.String(length=80), nullable=True))
    op.drop_column('user_profile', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('user_profile', 'username')
    op.drop_column('user_profile', 'userid')
    op.drop_column('user_profile', 'pic')
    # ### end Alembic commands ###
