"""empty message

Revision ID: e0698aa1440f
Revises: c7ed3b288562
Create Date: 2017-03-12 19:22:32.400757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0698aa1440f'
down_revision = 'c7ed3b288562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('pic', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('username', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'username')
    op.drop_column('user_profile', 'pic')
    # ### end Alembic commands ###
